CHROMA_COLLECTION_NAME = "subvenciones"
CHROMA_PERSIST_PATH = "../chromadb/"
# CHROMA_SENTENCE_TRANSFORMER = "all-MiniLM-L6-v2"
CHROMA_SENTENCE_TRANSFORMER = "paraphrase-multilingual-MiniLM-L12-v2"
LOG_FILE_PATH = "/logs/"